### ISSUE TITLE
problem in MEETING_SERVICE in web/assets/js/vid.js

### ISSUE THREAD

**Issue by ankitaivd** [architecturebytes/videoconf#2]
when we deine MEETING_SERVICE    that time APIGatewayURL is api gateway "Invoke URL" and route is "ANY" but  it will  reponsed as "404 not found"

**Comment by architecturebytes** [comment]
Have you created the 'HTTP' API Gateway with a route which is integrated with lambda function? 
Is it auto-deployed to 'default' stage?

**Comment by ankitaivd** [comment]
i created he 'HTTP' API Gateway with a route which is integrated with lambda function and it is auto-deployed to 'default' stage. this MEETING_SERVICE = "https://<APIGatewayURL>/<route>"
here APIGatewayURL= invoking url,oute=lamaba function

**Comment by ankitaivd** [comment]
please help on this

**Comment by ankitaivd** [comment]
I  use this in postman shows 500 error 
"
invoke url /routet?clientId=5sgvm7bxfnan4s4hnzu3a"
 request json is {
    "action": "DO_MEETING",
    "MEETING_ID": "null",
    "USERNAME": "gfhgj"
}

**Comment by ankitaivd** [comment]
Hello, 
my lamda function problem is solved. I need the help on allowing meeting and voice and video on off option. please help me on that.
